packages:
  sensasoil_common: !include ../../common/config/common.yaml
  entities: !include entities.yaml

substitutions:
  HARDWARE_VERSION: "3.0"
  HARDWARE_VERSION_FLAT: "3-0"
  FIRMWARE_VERSION: !env_var FIRMWARE_VERSION
